CDSETool/CDSETool

src/cdsetool/cli.py, src/cdsetool/monitor.py, src/cdsetool/query.py
Windows does not support `Signal.signal(signal.SIGWINCH, handler)`, so we disable it entirely
fixes #3
=> Disable listening to SIGWINCH on NT

LICENSE
LICENSE is empty at the moment, but should be MIT with SDFI copyright
=> Chore: Add License

README.md, src/cdsetool/query.py
Use a larger batch size by default, to reduce amount of requests
=> Update default query batch size

.github/dependabot.yml
Add the github-actions package-ecosystem
to dependabot so CI actions are kept
up to date.
Actions aren't typically updated multiple
times per week, so run the check on a daily
basis.
=> dependabot: use for Github actions

src/cdsetool/download.py
Use the existing open file descriptor
instead of opening a new file descriptor
to the same file.
It is not clear to me if this has any
bearing for #67, but having fewer file
descriptors open will not make anything
worse.
=> download: use existing open fd

src/cdsetool/download.py, src/cdsetool/logger.py, tests/logger/logger_test.py
This adds support for clients to pass in
a configured logger object to get warning
logs on retries, and debug logs in general
when downloading.
The default logger is a no-op logger, so
default behavior remains unchanged.
=> Add optional logging

src/cdsetool/credentials.py
Get the current time right after the post
request returns, and calculate the expire
times from that point in time.
This minimizes the error of the token expire
times.
=> credentials: set expire based on post time

src/cdsetool/credentials.py
This is either some tricky logic that
deserves a comment, or a cut and paste
error.
=> credentials: remove duplicate line

src/cdsetool/download.py
This is what `stream_response_to_file` from the requests toolbelt package does, and that package resides alongside the requests package on Github.
Refs #67
=> download: write all received bytes to file

pyproject.toml, src/cdsetool/download.py
First commit renames some variables as preparation
for the second commit.
The second commit updates download_feature
to return None when it fails, and the filename
downloaded when it succeeds.
Fixes #59
=> download: return error on failure

.gitignore, src/cdsetool/download.py, src/cdsetool/query.py
Hello, I have made the changes just for the proxy feature, it can be used it the following way:
```Python
proxies = {'http': 'http_proxy', 'https': 'https_proxy'}
features = query_features(
"Sentinel1",
{
"startDate": "2020-12-20",
"completionDate": date(2020, 12, 25),
"processingLevel": "LEVEL1",
"sensorMode": "IW",
"productType": "IW_GRDH_1S",
"geometry": shape_to_wkt("path/to/shapefile.shp"),
},
proxies
)
list(
download_features(
features,
"path/to/output/folder/",
{
"concurrency": 4,
"monitor": StatusMonitor(),
"credentials": Credentials("username", "password"),
"proxies": proxies,
},
)
)
```
I tried to add the proxy to all the requests in the query and added the proxy in the session object in the download part, let me know if it work this time.
if the fields of proxies are not passed …
=> proxy feature on query and download

src/cdsetool/download.py
There is no need for an intermediate
variable, pass the file size directly
to the monitor.
=> download: inline single-use variable

src/cdsetool/credentials.py, src/cdsetool/download.py
PyJWT might throw an exception on connection
error, so wrap that into our own exception
so download can retry without token implementation details leaking into download.
=> download: retry token connection errors

src/cdsetool/query.py
The request might not succeed, in
which case the json() call will
give a mysterious:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Do a .raise_for_status() before
calling json() on the response.
This also throws an exception
in the face of the user,
but it's easier to understand
that something went wrong
with the HTTP request.
=> query: check return value of get

.github/dependabot.yml
I was trying to update to typer 0.10, but CDSETool dependencies are blocking that. Run dependabot on a daily basis so pull requests are generated "immediately" on a release.
=> dependabot: run on a daily basis

src/cdsetool/download.py
For some reason, the other end sends
fewer bytes than indicated by "Content-Length",
which causes urllib3 to throw an exception.
Catch the exception and retry the download.
=> download: retry connection errors

src/cdsetool/credentials.py, src/cdsetool/download.py
There are small windows of race
conditions with respect to expiration
times, so this kind of error is expected
to happen eventually.
Catch the error and retry when it happens.
=> Retry on ExpiredSignatureError

src/cdsetool/credentials.py
Windows/Python 3.12 can get to the check
in __ensure_tokens without having any
time passed. Set an initial time that
is in the past to force a token
refresh on creation.
Fixes #117
=> credentials: force initial token refresh

src/cdsetool/credentials.py
The website will frequently respond
500/502, so back off and try again when
that happens.
=> credentials: retry 500/502 response

src/cdsetool/credentials.py, src/cdsetool/query.py
The Copernicus web site sometimes responds 500 (along other error codes) to queries. Use the retry logic from credentials so queries are retried just like downloads.
This PR creates a merge conflict with #120 so one has to be merged before the other, but the changes are complementary.
=> query: re-use session/retry logic from credentials

src/cdsetool/query.py
The find can fail and return None,
so return nothing when that happens.
=> query: detect error condition

pyproject.toml, src/cdsetool/_processing.py, src/cdsetool/cli.py, src/cdsetool/credentials.py, src/cdsetool/download.py, src/cdsetool/monitor.py, src/cdsetool/query.py, tests/credentials/credentials_test.py, tests/logger/logger_test.py, tests/query/query_features_test.py, tests/query/query_test.py
Add a pyright config section to pyproject.toml, type annotations to many methods/functions, and a py.typed marker so clients to the library can use the types when type checking their code.
Added some string quotes to a couple of tests to please the type checker, and changed some code to make it easier for the type checker to figure out what is going on.
=> Add type annotations

.github/workflows/lint.yml, .github/workflows/pytest.yml
With the introduction of pyright in #141, having automated checks would be ideal.
This PR aims to introduce basic type checking as part of CI pipeline
=> Chore: Run pyright as github action

src/cdsetool/download.py
The exception does not have a message,
so the logs get an empty line with "WARNING".
Print a message instead of printing
the exception.
=> download: log message on token expiry

src/cdsetool/query.py
Python 3.12 prints a deprecation
warning:
DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
so test for None instead.
=> query: fix Python 3.12 warning

src/cdsetool/credentials.py
I initially set the retry-value
to 2 to prevent spamming bad login
credentials at the Copernicus
site, but this value is too low
when the site responds with 503.
Bump the value to 15 so people
don't get an exception thrown
in their face because of intermittent
issues with the Copernicus site.
=> credentials: retry more to login

src/cdsetool/download.py
The exception does not have a message,
so the logs get an empty line with "WARNING".
Print a message instead of printing
the exception.
This is a sibling to commit 7ed5b74ae3f.
=> download: log message on token connection error

.github/workflows/lint.yml, .github/workflows/pytest.yml, pyproject.toml
The CI tests fail for Python 3.8
because of some changes in Fiona
and/or Geopandas. The Python 3.8
security support ends 31 October 2024.
Rather than spending time on fixing
something that will be obsolete
in a little more than a month,
drop the support for Python 3.8 now,
so the CI isn't constantly red.
=> Drop Python 3.8 support

src/cdsetool/query.py
This replicates the logic from download_feature to retry instead of crashing when there are HTTP errors and non-200 responses.
=> query_feature: retry on HTTP errors

src/cdsetool/download.py
Append .zip to .SAFE (for Sentinel 1 and 2).
Include a simple if for Sentinel 3 (which has a suffix of SEN3) to append .zip there also.
Closes #180
=> Append .zip to .SAFE instead of replacing it. Treat Sentinel 3 files accordingly

.gitignore
There is no IDE-configuration committed
to this repository, so ignore the directories
that IDEs use to keep track of their settings.
=> gitignore: add VSCode/PyCharm dirs

tests/query/query_features_test.py
With the pyright CI job, this check is
already performed elsewhere.
=> tests: remove type check test

.github/workflows/lint.yml, pyproject.toml, src/cdsetool/_processing.py
This replaces black with Ruff.
The coding style of Ruff is based
on black so there are no significant
differences as evidenced by the size
of the diff of this PR. The main
difference is that Ruff is significantly
faster.
Ruff also provides the functionality
of isort and Flake8 with various plugins,
but this PR just replaces the formatting
parts done by black, any further linting
can be done in a future PR.
=> Use Ruff instead of black

.github/workflows/lint.yml
Astral just forked the Ruff action
and state they will overhaul it,
so switch to the "official" version
of the Ruff action.
=> CI: use official Ruff action

.github/workflows/lint.yml, pyproject.toml, src/cdsetool/_processing.py, src/cdsetool/cli.py, src/cdsetool/credentials.py, src/cdsetool/download.py, src/cdsetool/monitor.py, src/cdsetool/query.py, tests/credentials/credentials_test.py, tests/logger/logger_test.py, tests/query/query_features_test.py, tests/query/query_test.py
This gives deterministic order
of imports, which increases the chance
that Github will be able to merge
independent pull requests without
manual intervention.
=> Enable Ruff "I" lint category

pyproject.toml, src/cdsetool/credentials.py, src/cdsetool/logger.py, src/cdsetool/monitor.py, src/cdsetool/query.py, tests/credentials/credentials_test.py, tests/query/query_features_test.py
Add some more type signatures on the regular code, and put in "Any" on all the mocker objects in the tests.
There are still missing type signatures in the code base, but this brings us closer to being able to enable `reportMissingParameterType` so pyright in the CI automatically enforces type signatures on new code.
=> Add more type signatures

src/cdsetool/query.py, tests/query/query_test.py
Move some code around so the code will work better under Python -O (where asserts are removed) when bad parameters are passed.
This will conflict with #196, I prefer to have this merged first.
=> Improve behavior when running under Python -O

src/cdsetool/credentials.py, src/cdsetool/query.py, tests/query/query_features_test.py, tests/query/query_test.py
The Copernicus servers give intermittent failures causing failures. Increase the number of retries in the Retry object, and add the retry+sleep-logic from download to more parts of query.
Also make a type signature more specific, and tweak the signature of "internal" parameter validation functions so they never get called with a None-parameter.
Edit: add an option to skip search term validation entirely. This eliminates those API calls to the remote server, but the remote server will obviously be unhappy if you disable search term validation and provide faulty search terms.
=> query: retry even more

pyproject.toml
The Ruff action looks for Ruff version
in dependency-gruops.dev, so make
such a group for Ruff.
This prevents pylint upgrades from
failing because the most recent
Ruff changed something in the formatting.
Keep the other development dependencies
in their previous section since
pip has not yet implemented the support
for dependency-groups.
=> pyproject: add dependency-groups.dev for Ruff

src/cdsetool/query.py
Make the CI green by adding a temporary
pyright ignore.
=> query: ignore type error temporarily

.github/workflows/scan.yml
This will populate the security
tab in Github with scan results.
=> CI: add security scan workflow
